version: "1.0.0.{build}"
image: Visual Studio 2019

before_build:
  - ps: "dotnet restore"
build:
  project: GEmojiSharp.sln
  verbosity: minimal
test_script:
  - ps: "dotnet test .\\tests\\GEmojiSharp.Tests\\GEmojiSharp.Tests.csproj"
