name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish ./samples/GEmojiSharp.Sample.BlazorWebAssembly/ --configuration Release --output build
    - name: Fix index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/GEmojiSharp\/" \/>/g' ./build/wwwroot/index.html
    - name: Add .nojekyll
      run: touch ./build/wwwroot/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: ./build/wwwroot
        clean: true
